名字: Build APK

在: [推]

工作:
建设:
连续运行: Ubuntu-最新版
步伐:
    - 使用: 动作/签出@v3
    - 使用: 操作/设置-python@v4
随着:
大蟒版本: '3.10'
    - 奔跑: 点安装生成器
    - 奔跑: buildozer android调试
    - 使用: 动作/上传-工件@v3
随着:
名字: 麻将-艾
小路: bin/*。apk
